-- AlterTable
ALTER TABLE "Availability" ADD COLUMN     "enabled" BOOLEAN NOT NULL DEFAULT true,
ALTER COLUMN "startTime" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "endTime" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Booking" ALTER COLUMN "dateTime" SET DATA TYPE TIMESTAMPTZ;
